# This is a basic workflow to help you get started with Actions

name: macOS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch/tag/commit"
        required: true
        default: dart7/main
      compiler:
        description: "Compiler: {gcc, clang}"
        required: true
        default: "clang"
      build_type:
        description: "Build type: {Release, Debug}"
        required: true
        default: "Release"
      build_dartpy:
        description: "Build dartpy: {ON, OFF}"
        required: true
        default: "ON"
  schedule:
    # Runs at 2 UTC every other day
    - cron: "0 2 * * 0/2"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  manual_build:
    if: github.event_name == 'workflow_dispatch'

    # The name of jobs
    name: macos.${{ github.event.inputs.build_type }}

    # The type of runner that the job will run on
    runs-on: macos-10.15

    env:
      COMPILER: ${{ github.event.inputs.compiler }}
      BUILD_TYPE: ${{ github.event.inputs.build_type }}
      BUILD_DARTPY: ${{ github.event.inputs.build_dartpy }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: dartsim/dart
          ref: ${{ github.event.inputs.ref }}
      - name: Install Dependencies
        run: .ci/install_osx.sh
      - name: Build
        run: sudo -E .ci/build.sh

  schedule_build:
    if: github.event_name != 'workflow_dispatch'

    # The name of jobs
    name: macos.${{ matrix.compiler }}.${{ matrix.build_type }}

    # The type of runner that the job will run on
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]
        build_dartpy: [ON]

    env:
      COMPILER: ${{ matrix.compiler }}
      BUILD_TYPE: ${{ matrix.build_type }}
      BUILD_DARTPY: ${{ matrix.build_dartpy }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: dartsim/dart
          ref: dart7/main
      - name: Install Dependencies
        run: .ci/install_osx.sh
      - name: Build
        run: sudo -E .ci/build.sh
