# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
    # Runs at 2 UTC every other day
    - cron: '0 2 * * 0/2'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The name of jobs
    name: ${{ matrix.os }}.${{ matrix.platform }}.${{ matrix.build_type }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-bionic, ubuntu-focal, ubuntu-impish]
        platform: [linux/amd64]
        build_type: [Release]
        codecov: [OFF]
        check_format: [OFF]
        num_cores: [MAX]
        build_examples: [ON]
        build_tutorials: [ON]
        build_dartpy: [ON]

    env:
      # Hosted on: https://hub.docker.com/repository/docker/dartsim/dart-dev
      DART_DEV_IMAGE: dartsim/dart-dev
      DOCKER_TAG: ${{ matrix.os }}-v7.0
      PLATFORM: ${{ matrix.platform }}
      COMPILER: gcc
      BUILD_TYPE: ${{ matrix.build_type }}
      BUILD_DARTPY: "${{ matrix.build_dartpy }}"
      CODECOV: ${{ matrix.codecov }}
      CHECK_FORMAT: ${{ matrix.check_format }}
      NUM_CORES: ${{ matrix.num_cores }}
      BUILD_EXAMPLES: ${{ matrix.build_examples }}
      BUILD_TUTORIALS: ${{ matrix.build_tutorials }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: dartsim/dart
          ref: dart7/main

      - name: Pull dev container
        run: docker pull $DART_DEV_IMAGE:$DOCKER_TAG
      - name: Build
        run: |
          docker run \
            -e CI=true \
            --platform $PLATFORM \
            --volume $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            --env-file ./.ci/docker/env.list \
            $DART_DEV_IMAGE:$DOCKER_TAG \
            /bin/sh -c "cd $GITHUB_WORKSPACE && ./.ci/build.sh"
